- neutron/db/common_db_mixin.py
- neutron/db/db_base_plugin_v2.py
- neutron/db/sqlalchemyutils.py
The paginate_query method was copied from nova which was copied
from glance. Now it is available in oslo_db.
Check and convert the sort keys and sort directions for
consumption by the oslo_db version of the method, and fix up
some grammar in the exception messages.
This work is related to the neutron-lib effort. The lib should
not propagate neutron's copy of paginate_query().
Related-Blueprint: neutron-lib
Change-Id: Ie7da16b94fa2023c9c3d84d96d55f33d0f76903f
> Use paginate_query from oslo_db

- neutron/db/db_base_plugin_v2.py
- neutron/tests/unit/db/test_db_base_plugin_v2.py
An API request for a portlisting filtered by ip-address or subnet
failed with a 500, as get_collection_query() in _get_ports_query()
already sets a limit on the query. Subsequent query.filter() calls
fail with an exception. To circumvent this we disable the SA
assertions around this query, including _no_limit_offset() until
a real fix is available. We can do this because the assertion is
in place to prevent someone to apply a filter() on a already limit()ed
query, as the filter will be executed first in any case - but this is
exactly what we want here.
The bug was introduced by Openstack change-id Ia6e916a9dae5f5ef203259c3d1c6e1c30445c07d
and commit 5b7c8c3e27dab38a3b336bb3ac0a87b98944b6cf
> Temporary disable SA assertions for port list with limit

- neutron/extensions/securitygroup.py
Our customers want to be able to prohibit certain colleagues from
changing the security_groups. For this, we have to tell neutron to
explicitly enforce policy for `Port.security_groups`.
After that, neutron checks for `update_port:security_groups` and
`create_port:security_groups` in addition to `update_port` and
`create_port`.
> Add explicit policy-enforcement for port.security_groups

- neutron/plugins/ml2/drivers/linuxbridge/agent/linuxbridge_neutron_agent.py
ensuring only one bond subinterface is assigned to the bridge at any
time
> remove bond interfaces from bridge before adding new ones

- neutron/db/db_base_plugin_v2.py
- neutron/tests/unit/extensions/test_address_scope.py
This commit fixes incorrect check for network address_scope affinity. Before this changes the function `_check_subnetpool_address_scope_network_affinity` compared lists of subnets related to subnet pools, and it works for upstream because they use 1 to 1 relation for `subnet` -> `subnet_pool` inside one network. But in our infrastructure different subnet pools in one network are valid configurations, so we have to check exactly `address_scope` inside each subnet_pool and they should be the same. This commit adds +1 database query per request for POST/PUT actions for subnet pool API, which in our reality will not add a significant load.
> Fix check for network address scopes affinity.

- neutron/plugins/ml2/extensions/dns_integration.py
- neutron/tests/unit/plugins/ml2/extensions/test_dns_integration.py
In case the port notification is handled after it related subnet was deleted,
an attribute error was rised. This commit will gracefully handle this case.
> dns_integration: fix attribute error for deleted subnet race condition

- neutron/db/securitygroups_db.py
- neutron/extensions/securitygroup.py
- neutron/tests/unit/db/test_securitygroups_db.py
This Commit adds `shared` field for security_group object to use for filtering in Oslo policies. Related to the bug: https://bugs.launchpad.net/neutron/+bug/1933242
> Add field shared for SG RBAC.

- neutron/db/l3_db.py
Floating IP ports should not have a project_id assigned to them as they
are not managed by the owner of a project, but by OpenStack itself. With
a project_id assigned they also count towards the port quota of said
project, which they should not. Therefore, we do not set a project_id
anymore on Floating IP creation for the Floating IP port. This is in
line with the behaviour we currently have for gateway interfaces of
routers.
Change-Id: I053d48166141e5cdbd39a1235a43b06d64478bc1
Closes-Bug: #1949767
---
Upstream backport
> Do not set project_id for floating ip ports

- neutron/plugins/ml2/extensions/dns_integration.py
- neutron/tests/unit/plugins/ml2/extensions/test_dns_integration.py
- releasenotes/notes/fix-port-dns-assignment-9d916d77522abd65.yaml
When a port is created the dns-assignment (dns-domain part)
was always taken form Neutron config dns_domain which is not
always true, since it could be Neutron network dns_domain or
the dns_domain sent when creating the port
Change-Id: I7f4366ff5a26f73013433bfbfb299fd06294f359
Closes-Bug:1873091
> Sync the dns-assignment with the actual designate dns-domain

- neutron/agent/linux/ip_lib.py
- neutron/privileged/agent/linux/ip_lib.py
For a linuxbridge-agent the startup performance gets worse the more
networks are scheduled onto the agent. One factor in this is that
parsing and transporting all netlink attributes for all interfaces takes
a long time. This makes functions like get_link_devices() pretty slow.
The more interfaces there are the slower it gets.
To prevent this an attribute filter is introduced to get_link_devices()
and to make_serializable(). Only specified attributes are serialized for
transport from each interface. As attributes can also be nested, this
can save up a lot of processing time, especially when only the interface
name is needed by the caller.
get_devices_info() now allows interface attributes to be restricted to a
subset as well. The function will determine which netlink attributes
need to be …
> Restrict query of iface attrs in linuxbridge agent

- neutron/agent/linux/ip_lib.py
- neutron/privileged/agent/linux/ip_lib.py
As OpenStack does <80 chars per line, so do we in our Neutron fork.
> [pep8] Fix overlong lines in agent code

- neutron/agent/linux/ip_lib.py
A missing ',' merged two fields in get_devices_info(), causing the
fields to be missing from the resulting dictionary.
> Fix wrong fields in get_devices_info() for linuxbridge

- neutron/db/securitygroups_db.py
This PR fixes shared `field` for Security Groups that were not shared. Before this fix we can see `shared=true` for any SGs.
> Fix security groups shared field.

- neutron/db/l3_db.py
- neutron/tests/unit/db/test_l3_db.py
Upstream Neutron has the assumption that all subnets of a network are in
the same subnet pool (and therefore same address scope), while our brand
of Neutron requires all subnets in a network to be either in the same
address scope or in no address scope at all.
Neutron adds the address scope to each port in the l3 router sync data,
but looks at all subnets present in the network. We now change this
behavior to only add the address scope when the router port is actually
in a subnet with this address scope. With this DAPNets (Directly
Accessible Private Networks) and non-DAPNets can live in peace together.
> Only set address scope when present for l3 sync data

- neutron/db/db_base_plugin_common.py
- neutron/db/db_base_plugin_v2.py
- neutron/tests/unit/db/test_db_base_plugin_v2.py
- [_create_db_port_obj] re-generate mac address if collision is detected
- [db_base_plugin_common] allocate mac_address uniquely across all networks
> mac address uniq

- neutron/db/ipam_backend_mixin.py
- neutron/tests/unit/db/test_ipam_backend_mixin.py
The current implementation does not allow subnets from different address
scopes in a network. For DAPnets we need to relax that constraint so we
allow subnets from the same address scope as well as subnets with no
subnet pool (and hence no address scope) and subnets with the same
address scope in a network.
> Relax check on subnet pools to just satisfy same address scope

- neutron/db/db_base_plugin_common.py
- neutron/db/db_base_plugin_v2.py
- neutron/plugins/ml2/plugin.py
- neutron/tests/unit/db/test_db_base_plugin_v2.py
The Cisco IOS XE platform drops any frames with a mac address that it has bound
on a local interface, no matter which VRF they are in. Openstack generates mac
addresses randomly and checks onlyh if the address is already used in the
current network. We implemented global mac address duplicate checking in
1a58780b81, but had to notice that ironic baremetal deployments may generate 2
ports in different subnets with the same IP. However this is only done on an
update and an update is an admin only action. Hence we relax the check for
update operations to only be network-wise unique while the create check must
satisfy a globally unique constraint.
> Mac address must only be globally unique on create

- neutron/plugins/ml2/plugin.py
The feature was added for nova live migration
(see https://review.opendev.org/c/openstack/neutron/+/414251/74/neutron/plugins/ml2/plugin.py#2005). Manila wants to do share live migration, and needs to modify its ports in a similar fashion: issue port binding upfront to determine the segmentation id in the target network segment.
depends on [new constant 'DEVICE_OWNER_MANILA_PREFIX' in neutron-lib](https://github.com/sapcc/neutron-lib/pull/2)
> allow manila ports to do multiple port binding for ML2

- neutron/agent/linux/dhcp.py
- neutron/tests/unit/agent/linux/test_dhcp.py
When talking to dnsmasq using DNS over tcp dnsmasq will fork out for TCP connections. Forked processes will stay until all connections have been closed, meaning that dangling connections will keep the processes and with that will also keep the tcp/53 port in listening state. On dnsmasq restart (e.g. on network update, subnet create, ...) the parent process is killed with SIGKILL and a new process is started. This new process cannot listen on tcp/53, as it is still in use by the old child with the dangling connection.
To prevent dangling dnsmasq connections on tcp we need to properly shutdown the child. This is done by first sending SIGTERM and only send a SIGKILL if the process is not shutting down proplerly. With that we get proper cleanup of all children and tcp will come up after a …
> Gracefully restart dnsmasq to not break tcp DNS

- setup.py
- tox.ini
We need this, because tox4 behaves differently than 3 and our pull-requests CI's image uses tox4 already.
Please also see the individual commits' message.
> Make Neutron ready for tox4

- neutron/db/db_base_plugin_v2.py
Upgrading from neutron ussuri to yoga, some database performance issues have been observed, resulting in more CPU time required by the db.The most executed query (port list) introduced a select distinct, resulting in the increase in used CPU time. Details about the patch [explicit select condition in sql query](https://opendev.org/openstack/neutron/commit/923284fc3791949d93d7ded9820a44f98fc734b8)
>   Reverting - Use explicit select condition in SQL query in "_port_filter_hook"

- neutron/agent/metadata/agent.py
- neutron/tests/unit/agent/metadata/test_agent.py
We want to get a better impression of what our users do with our metadata service and for this we want to improve the logging. The current logging logs part of the request (part by eventlet.wsgi, part by Neutron itself) or the complete ports request ("which ports do belong to the requester) as a multiline string representation of the request object.
To make debugging this easier for us we now log an extra single line for each request, containing many informations, as the current OpenStack network, client ip, user-agent, request path etc., which can then be easily consumed by some log parser (fluentd + grok in our case).
> Parsable logging for metadata service requests

- custom-requirements.txt
To protect the neutron api, a rate limiting middleware based on [openstack-watcher](https://github.com/sapcc/openstack-watcher-middleware) and [openstack-rate-limit](https://github.com/sapcc/openstack-rate-limit-middleware), shall be introduced. The latter one depends on the watcher middleware.
> neutron api rate limiting dependencies

- neutron/agent/metadata/agent.py
When sending an OPTIONS request to the metadata agent this request gets proxied to Nova, which then returns an empty HTTP response with content-length: 0 and no content-type key. This results in a KeyError, when we try to access this attribute. Using get() solves this and results in sending no content-type header to the client who requested this.
In our environment this can be reproduced with:
curl http://169.254.169.254/lol -X OPTION
> Don't break metadata with missing content-type

- neutron/agent/linux/dhcp.py
- neutron/tests/unit/agent/dhcp/test_agent.py
- neutron/tests/unit/agent/linux/test_dhcp.py
When multiple subnets are configured in the same network, the DHCP agent will choose the first suitable subnet with a gateway ip set as default gateway, where the subnets are in a generally stable, but arbitrary order. In some cases only some of the subnets in a network actually have a router in it, meaning a DHCP agent might loose Internet access (used for example for DNS).
Now we sort the subnets before selecting a default gateway. Subnets are sorted first by if their gateway ip is present on a port in the network and then by their created_at time, so we always have a stable order. Also, using the first created subnet seems like a good decision, as it will probably be the one with the least fluctuations. We won't filter for a router port, as the user could also provide a custom router …
> Prefer default gw with ip on port on DHCP Agent

- neutron/agent/linux/dhcp.py
- neutron/cmd/sanity/checks.py
- neutron/cmd/sanity_check.py
- neutron/conf/agent/dhcp.py
- neutron/tests/unit/agent/linux/test_dhcp.py
The motivation is to assist the upstream DNS resolvers in identifying the clients using the neutron dnsmasq resolvers.
The actual goal is monitoring of the DNS traffic for suspicious activity and uncovering compromised systems.
This is done by passing each client's IP address and network id to the upstream resolvers by adding that information as eDNS payload to the DNS query going out.
If this boolean option is toggled then the following two command line options will be appended to dnsmasq:
`--add-cpe-id=<network_id>`
`--umbrella`
The former will add the network id to eDNS option 65074.
The latter will add the client IP to eDNS option 20292.
The `--umbrella` option was introduced in dnsmasq 2.86.
A dnsmasq version check is in place to make sure the option does not get activated if the …
> Introducing the edns_client_fingerprint option

- neutron/db/extraroute_db.py
- neutron/tests/unit/db/test_extraroute_db.py
When handling the deletion of extra routes we need to handle the case that the route is already deleted by another call in the time we have fetched the extra routes and try to delete it. This is a classic race condition when two calls try to update the routes of a router at the same time.
> Don't delete already deleted extra router routes

- custom-requirements.txt
The driver is no longer needed in our infra and therefore doesn't need to be part of our image anymore.
> Remove ucsm driver from custom requirements

- neutron/agent/linux/dhcp.py
- neutron/conf/agent/dhcp.py
- neutron/tests/unit/agent/linux/test_dhcp.py
When we have a network with stateful DHCPv6 we still need router advertisements to tell the hosts the prefix length of the current network (else all hosts will just have /128 routes). In cases where a network does not have a router (or don't use an l3 plugin with ra support) we do not have something in the network that sends out ras (radvd itself is launched on the l3 agent with Neutron's default implementation).
Therefore we now let dnsmasq take over this task. With --enable-ra we enable dnsmasq's ra implementation. We use --ra-param=$iface,0,0 to deactivate that dnsmasq is advertising itself as default gateway. Params are (interface, use default ra-interval, router lifetime).
> Support on DHCP-agent for internal v6 networks

- neutron/services/externaldns/drivers/designate/driver.py
Currently Neutron-Designate integration will fail if target PTR record already exists. This can happen if the FIP was in use before or if PTR was created manually.
Instead of failing with error we want to update existing PTR in such case.
> Fix PTR logic for updates
